<a href="https://colab.research.google.com/github/soup511/python/blob/main/numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
print (a)

[1 2 3]


In [5]:
print (type(a))

<class 'numpy.ndarray'>


In [10]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
n=np.array([1,0,3],dtype=bool)
print(n)

[ True False  True]


In [34]:
np.arange(1,22,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [26]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.random.random((6,1))

array([[0.88676038],
       [0.26393902],
       [0.91709975],
       [0.90990604],
       [0.63129308],
       [0.07127423]])

In [51]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [232]:
a1=np.array([1,2,3])
a2= np.arange(12,dtype=int).reshape(6,2)
a3= np.arange(15).reshape(3,1,5)
a3

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [63]:
a1.ndim

1

In [65]:

a2.ndim

2

In [66]:
a3.shape

(3, 1, 5)

In [68]:
a1.shape

(3,)

In [70]:
a1.size

3

In [71]:
a3.itemsize

8

In [73]:
a1.itemsize

8

In [75]:
a3.dtype

dtype('int64')

In [77]:
a3.astype(np.int32)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]], dtype=int32)

In [81]:
a1= np.arange(10).reshape(2,5)
a2=np.arange(10,20).reshape(2,5)
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
a2*4

array([[40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76]])

In [84]:
a1>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [96]:
a2//a1

/tmp/ipykernel_1281/205399427.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a2//a1


array([[ 0, 11,  6,  4,  3],
       [ 3,  2,  2,  2,  2]])

In [98]:
np.max(a2)

np.int64(19)

In [99]:
np.sum(a1)

np.int64(45)

In [101]:
np.prod(a1)

np.int64(0)

In [103]:
np.min(a1,axis=0)

array([0, 1, 2, 3, 4])

In [113]:
np.var(a1,axis=1)

array([2., 2.])

In [114]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [117]:
a3= np.arange(20,30).reshape(5,2)
np.dot(a3,a2)

array([[515, 556, 597, 638, 679],
       [565, 610, 655, 700, 745],
       [615, 664, 713, 762, 811],
       [665, 718, 771, 824, 877],
       [715, 772, 829, 886, 943]])

In [119]:
np.log(a3)

array([[2.99573227, 3.04452244],
       [3.09104245, 3.13549422],
       [3.17805383, 3.21887582],
       [3.25809654, 3.29583687],
       [3.33220451, 3.36729583]])

In [157]:
np.round(np.random.random((4,2))*10)

array([[ 4.,  9.],
       [ 6., 10.],
       [ 9.,  9.],
       [ 3.,  8.]])

In [158]:
a1=np.array([1,2,3])
a2= np.arange(12,dtype=int).reshape(6,2)
a3= np.arange(15).reshape(3,1,5)


In [159]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [161]:
a2[3,0]

np.int64(6)

In [162]:
a3

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [165]:
a3[1,0,1]

np.int64(6)

In [166]:
a1

array([1, 2, 3])

In [170]:
a1[1:]

array([2, 3])

In [171]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [174]:
a2[-5]

array([2, 3])

In [175]:
a3

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [184]:
a2[:,1]

array([ 1,  3,  5,  7,  9, 11])

In [189]:
a3[::1,::3]

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [192]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [216]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [221]:
a1
for i in a1:
  print(i)

1
2
3


In [223]:
print(a2)
for i in a2:
  print(i)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]


In [219]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [226]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [227]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [228]:
np.transpose(a2)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [229]:
a2.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [231]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [233]:
a4= np.arange(12,dtype=int).reshape(3,4)
a5= np.arange(12,24,dtype=int).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [234]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [239]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [243]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [8]:
a=[i for i in range (10000000)]
b=[i for i in  range (10000000,20000000)]
c=[]
import time
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

2.2321393489837646


In [2]:
import numpy as np
a= np.arange(10000000)
b= np.arange(10000000,20000000)
import time
start =time.time()
c=a+b
print(time.time()-start)

0.03450489044189453


In [4]:
a=[i for i in range(1000)]
import sys
sys.getsizeof(a)

8856

In [8]:
a=np.arange(1000,dtype=np.int8)
sys.getsizeof(a)

1112

In [12]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
a[:,[1,2]]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [34]:
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[86, 95, 53, 22],
       [53, 20, 13, 81],
       [91, 18, 67, 97],
       [87, 41, 13, 86],
       [41, 62, 51, 55],
       [77, 80, 92, 98]])

In [35]:
a>50

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a[a>50].reshape(17,1)

array([[86],
       [95],
       [53],
       [53],
       [81],
       [91],
       [67],
       [97],
       [87],
       [86],
       [62],
       [51],
       [55],
       [77],
       [80],
       [92],
       [98]])

In [2]:
import numpy as np
a=np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])